version: '3.8'

services:
  mud-server:
    build: .
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev 